version: '3'
services:
  twitchbot-blue:
    build: ./twitchbot
    container_name: twitchbot-blue
    restart: always
    environment:
      FLASK_DEBUG: "development"
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      PREFIX: ${PREFIX_DEBUG}
      TOKEN: ${TOKEN}
      DATABASE_URL: ${SQLALCHEMY_DATABASE_URI_DEBUG}
    networks:
      - db
  web-blue:
    build: ./web
    container_name: web-blue
    restart: always
    networks:
      - db
    ports:
      - "${DEV_PORT}:${DEV_PORT}"
    env_file:
      - .env
    command: "python3 wsgi.py"
    volumes:
      - web-data:/web
  twitchbot-green:
    build: ./twitchbot
    container_name: twitchbot-green
    restart: always
    environment:
      FLASK_PROD: "production"
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      PREFIX: ${PREFIX}
      TOKEN: ${TOKEN}
      DATABASE_URL: ${SQLALCHEMY_DATABASE_URI}
    networks:
      - db
  web-green:
    build: ./web
    container_name: web-green
    restart: always
    networks:
      - db
    command: gunicorn "app:create_app()" -b 0.0.0.0:8001
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
networks:
  db:
    external: true

volumes:
  web-data:
