version: '3'

services:
  website:
    build:
      context: .
    volumes:
        - .flask-data:/flask  
    ports:
      - "8001:8000"

    container_name: ${CONTAINER_NAME}
    

volumes:
  flask-data:
