# Use the official Python image as the parent image
FROM python:3.11.1

# Set the working directory in the container
WORKDIR /app

# Copy the application files to the working directory
COPY . .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Add a Python virtual environment

